#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL
#
# @type Quadrotor Wide
#
# @maintainer Julian Oes <julian@oes.ch>
#

. ${R}etc/init.d/rc.mc_defaults

set MIXER quad_x
param set-default MC_YAWRATE_K 0.95
param set-default MC_YAWRATE_I 0.04
param set-default MC_YAW_P 1
